#!/bin/sh /etc/rc.common

START=90
STOP=10
USE_PROCD=1

PROG=/usr/sbin/tcpredir
CONFIG=tcpredir

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -c "$CONFIG"
	procd_set_param respawn 3600 5 5
	procd_set_param file /etc/config/tcpredir
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	procd_send_signal tcpredir '' HUP
}

service_triggers() {
	procd_add_reload_trigger tcpredir
}
